### ISSUE TITLE
Installing js-qs appears to break subsequent calls to 'npm install'

### ISSUE THREAD

**Issue by jamesrichards** [m59peacemaker/js-qs#4]
Hello,

This might be an edge case issue. I seem to be having issues with subsequent calls to `'npm install'` since installing this module.

Steps to repro:
1. `npm install @m59/qs` - Installs successfully and I am able to use the module in project.
2. `npm install` - A subsequent call to 'npm install'. Our build server runs this command every time a deployment goes out the door. Node returns the following:

```
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path C:\Development\InchcapeTS\Inchcape.Website\node_modules\@m59\qs
npm ERR! code EISGIT

npm ERR! git C:\Development\InchcapeTS\Inchcape.Website\node_modules\@m59\qs: Appears to be a git repo or submodule.
npm ERR! git     C:\Development\InchcapeTS\Inchcape.Website\node_modules\@m59\qs
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Development\InchcapeTS\Inchcape.Website\npm-debug.log
```

Node install ends at this point and doesn't go any further. Here's a copy of my npm-debug.log if it helps: https://pastebin.com/kq6g0jPE

It's worth noting I'm able to circumvent the issue by manually deleting the '@m59' folder module within node_modules. Then running npm install again works just fine.

I did find this issue on an [older, unrelated repo](https://github.com/shama/napa/issues/53) - but it does look similar to what I'm experiencing - if it helps! 

Thanks

**Comment by m59peacemaker** [comment]
That supposedly means there is a `.git` directory in there, I guess at `node_modules\@m59\qs`. I don't see anything in my repo that would cause that. Can you hop into that directory while the problem is occurring and verify that there is a git project there and checkout its log / info? Maybe we can figure out where it is coming from.

**Comment by m59peacemaker** [comment]
I got a minute to check it out. The git repo does end up published somehow. I've never had that happen before. No idea why. I'll fix it here in a sec.

**Comment by m59peacemaker** [comment]
It appears that when I published that documentation update, I got hit with an npm bug https://github.com/npm/npm/issues/19073 where npm is publishing the git directory. I explicitly ignored it in `.npmignore` and published again. https://github.com/m59peacemaker/js-qs/commit/f314b93109db13b99660d7f1aa3238d1efb185bb

**Comment by jamesrichards** [comment]
Wow - that's a first for me. Who'd have thought simply updating your docs could have such an effect! 

Thanks again for the swift turnaround - really appreciate it.
